<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\KalibrasiCustomer;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    public function run()
    {
        $companyNames = [
            "PT Surveyor Indonesia (Persero)",
            "PT. MUTUAGUNG LESTARI TBK",
            "PT Federal Nittan Industries",
            "PT. Arkanindoplast Utama",
            "PT. MUTUAGUNG LESTARI TBK - SURABAYA",
            "PT. Mutuagung Lestari Tbk Cabang Jambi",
            "PT. MUTUAGUNG LESTARI Tbk - BANJAR BARU",
            "PT. Teknologi Optima Kalibrasi",
            "PT. TORAJA PANGESTU",
            "PT. Kalibrator Uji Utama",
            "PT. Mitra Digital Instrumentasi",
            "PT. Rukun Sejahtera Teknik",
            "PT. Indofood CBP Sukses Makmur Tbk",
            "PT. Karya Instrumentasi Global",
            "PT Diamond Cold Storage",
            "PT. MEDIALAB INDONESIA",
            "PT. Akurasi Prima",
            "PT Anugrah Analisis Sempurna (AAS Laboratory)",
            "PT. Amerta Indah Otsuka",
            "PT INTRALAB EKATAMA",
            "PT. Jambi Lestari Internasional",
            "PT. Hitachi Construction Machinery Indonesia",
            "PT Mulia Abadi Instrumindo",
            "CV Jaya Abadi Instrument",
            "PT. MUTUAGUNG LESTARI TBK - SIDOARJO",
            "PT. Global Mandiri Instrumentasi",
            "PT. Calfindo Berkah Mandiri",
            "PT. Forsta Kalmedic Global",
            "PT. ENVIROTAMA SOLUSINDO",
            "PT. Beta Pharmacon",
            "CV RE CALIBRATE INDONESIA",
            "PT. Mitra Enviro",
            "UPTD Laboratorium Lingkungan Kab. Bekasi",
            "PT. SUPERINTENDING COMPANY OF INDONESIA",
            "PT Finura Sinergi Analitika",
            "PT Saraswanti Indo Genetech",
            "PT. Mandiri Transforma Global",
            "PT. Inti Surya Laboratorium",
            "PT GLOBAL MEDIPRO INVESTAMA",
            "PT. Delta Indonesia Laboratory",
            "PT Prakarsa Adi Sahya",
            "PT Mutuagung Lestari Tbk - Batam",
            "PT. Megah Persada Abadi",
            "PT. Kleenviro Dinamika Utama",
            "PT LAPI LABORATORIES",
            "PT Pananjung Anugrah Solution",
            "PT. Mutuagung Lestari Tbk - Samarinda",
            "PT. MUTUAGUNG LESTARI TBK - PEKANBARU",
            "PT. EQUILAB INTERNATIONAL",
            "PT. Global Quality Analitical",
            "PT. Phapros Tbk",
            "PT. TEKNILAB ANALISA LINGKUNGAN",
            "PT Envitek Indonesia Jaya",
            "PT. Sumber Buah Abadi",
            "PT. MEDIALAB INDONESIA - SIDOARJO",
            "PT SUPERINTENDING COMPANY OF INDONESIA",
            "PT. Mutu Global Instrumentasi",
            "PT. SUKANDA JAYA",
            "PT. Mandom Indonesia",
            "PT. Delta Instrumentasi",
            "PT. LANGKAH ANAK BANGSA",
            "PT. Patra Solusi Instrumentasi",
            "PT. Unilab Perdana Cabang Surabaya",
            "PT Adhikarilab Indonesia",
            "PT. Pananjung Anugrah Solution",
            "Laboratorium Terpadu IPB",
            "PT. Sambara Jaya Wisesa",
            "PT. ATMOS LABORATORIUM INDONESIA",
            "PT Ganesha Inti Persada",
            "PT. Nippon Shokubai Indonesia",
            "PT SALINGGA KONSULTAN JAYA ENV",
            "PT Segara Kencana",
            "PT. PHC INDONESIA",
            "PT HAS Environmental",
            "PT. Pratama Graha Semesta",
            "PT. Bengawan Tirta Rekayasa",
            "PT GLOBAL INSTRUMENT SERVICES",
            "PT. Air Bandung Timur",
            "PT ECOSINDO LABORANUSA",
            "Pak Taufiq",
            "PT Indolab Utama",
            "Perumda Air Minum Jaya (PAM JAYA LAB TIMUR)",
            "Perumda Air Minum Jaya (PAM JAYA LAB PUSAT)",
            "Perumda Air Minum Jaya (IPA)",
            "Perumda Air Minum Jaya (PAM JAYA LAB BARAT)",
            "PT. AIR BERSIH JAKARTA",
            "PT. Kalbio Global Medika",
            "PT. Arfindo Bersinar",
            "PT. Eka Akurasi Envitama",
            "Balai Veteriner Subang",
            "PT. Qualis Indonesia",
            "PT Oilaboratorium Lingkungan Indonesia",
            "PT Argha Karya Prima Industry Tbk",
            "PT Instrumen Indo Utama",
            "PT. Laboratorium Solusi Indonesia",
            "PT . INTI KARUNIA SENTOSA",
            "PT Enerviro Rinata Adi",
            "PT. Sharma Indotama Indonesia",
            "PT. ERA MITRA PERDANA",
            "PT. LAWANA SUKSES NUSANTARA",
            "PT. PADI HIJAU BUANA",
            "PT. SECM TECH INDONESIA",
            "PT. MUTUAGUNG LESTARI Tbk - Medan",
            "PT. Menarini Indria Laboratories",
            "PT SECM Tech Indonesia",
            "CV TRI ANUGRAH FAJAR",
            "PT AESER TABAYO INDONESIA",
            "Balai K3 Bandung",
            "PT. Earth House Indonesia",
            "PT. MUTIARA LABORATORIUM MANDIRI",
            "PT Prysmian Cables Indonesia",
            "PT Tri Daya Maxima",
            "PT BAKRIE AUTOPARTS",
            "PT ROLAN BETUAH JAYA",
            "BPAFK Surakarta",
            "PT AGROVETA HUSADA DHARMA",
            "PT ONEJECT INDONESIA",
            "PT. VIRZIC GLOBAL INDONESIA",
            "PT. MULTI NITROTAMA KIMIA",
            "PT. WATER LABORATORY NUSANTARA INDONESIA",
            "PT. MAXLAB SAINTEK INDONESIA",
            "PT ITEC SOLUTION INDONESIA",
            "PT Tunggal Idaman Abdi",
            "Bapak Robbi Iskandar",
            "PT Jump Consulting",
            "PT. Envilab Indonesia",
            "PT Mitra Solusi Energi Berkelanjutan (EnerCoss)",
            "PT. ARASY ANALITICAL RESEARCH LABORATORIES",
            "PT. AZBIL BERCA INDONESIA",
            "PT. Advanced Analytics Asia Laboratories",
            "PT. ZAMURAH INTI PERKASA",
            "PT. Aneka Tambang UBPP Logam Mulia",
            "PT BUMI VENTILA INDONESIA",
            "Balai Standardisasi dan Pelayanan Jasa Industri Pontianak",
            "PT. MUTUAGUNG LESTARI Tbk - PANGKALAN BUN",
            "PT Global Presisi Indonesia",
            "PT. Exactacal Technology Solution",
            "PT. DINAMIKA KALIBRASI INDONESIA",
            "PT Intertek Utama Services",
            "PT Hart Testing Services",
            "PT. JAYA SAIN TEKNO",
            "PT Taikisha Indonesia Engineering",
            "PT. Puskalindo Medistri Scientama",
            "PT. ECOSTAR LABORATORIES",
            "PT DEFAN INSTRUMENTS",
            "PT Trio Putera Utama",
            "PT Promatrix Facilities Management",
            "PT. Mettler Toledo Indonesia",
            "PT RUDOLF CHEMICALS INDONESIA",
            "PT Satya Abadi Pharma",
            "PT RTI Group",
            "CV Indohitech",
            "PT KMI Wire and Cable Tbk",
            "PT. Hongfa Electronic Indonesia",
            "PT. Indofood CBP Sukses Makmur Tbk",
            "PT. SINAR TRIKARYA MANDIRI",
            "PT. Mutuagung Lestari Tbk - Pontianak",
            "PT. SISTEM DIRGANTARA INOVASI TEKNOLOGI",
            "PT Medina Global Service",
            "PT. KARYA LABORATORIUM INDONESIA",
            "PT. KARUNIA JASINDO",
            "PT. Sari Enesis Indah",
            "PT HARTECH INDONESIA",
            "PT. Delta Primalab Saintifik",
            "PT Solusi Prima Visitama",
            "PT. Aisin Indonesia",
            "PT. Petrolab Services",
            "PT. Sentral Tehnologi Managemen",
            "PT. GRAHA MUTU PERSADA",
            "PT DITEK JAYA",
            "PT Sadikun Niagamas Raya",
            "PT. HYS SUKSES MEDIKA",
            "PT.DEXA MEDICA",
            "PT. Kansai Paint Indonesia",
            "BALAI BESAR PENGUJIAN MINYAK DAN GAS BUMI",
            "PT. INTERTEK UTAMA SERVICES",
            "PT Water Laboratory Nusantara Indonesia",
            "PT. SGS WLN INDONESIA - BOGOR",
            "PT. METROLOGI GLOBAL SOLUSI",
            "PT Air Bersih Jakarta",
            "PT. MUTUAGUNG LESTARI Tbk - MAKASSAR",
            "PT CBC INDONESIA",
            "PT PASCAL INSTRUMENTASI SERVICES",
            "PT. NATIONAL ANDALAN SERVICES",
            "PT. Aneka Tambang Setiabudi One",
            "PT YSP Industries Indonesia",
            "PT. Balai Besar Standarisasi Dan Pelayanan Jasa Industri Kulit Karet Dan Plastik",
            "PT. Starlab Analitik Indonesia",
            "PT BioSupport",
            "PT. ANDARU PERSADA MANDIRI",
            "CV. ALIF PUTRA PERDANA",
            "PT Waskita Niagaprima",
            "PT. ABBOTT INDONESIA",
            "PT Aneka Tambang Juanda",
            "PT Aneka Tambang Puri Indah",
            "PT Supreme Cable Manufacturing & Commerce Tbk.",
            "PT Valve Automation Indonesia"
        ];

        // Deduplicate while preserving order
        $uniqueCompanies = array_values(array_unique(array_map('trim', $companyNames)));

        foreach ($uniqueCompanies as $company) {
            KalibrasiCustomer::firstOrCreate(
                ['nama_pelanggan' => $company],
                [
                    'alamat_pelanggan' => 'Indonesia',
                    'kontak_person' => 'Bagian Pengadaan / Lab QC',
                    'no_hp_email' => 'contact@' . strtolower(preg_replace('/[^a-zA-Z0-9]/', '', substr($company, 0, 12))) . '.co.id',
                ]
            );
        }
    }
}
